[build]
  functions = "netlify/functions"
  
[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/auth/login"
  to = "/.netlify/functions/auth-login"
  status = 200

[[redirects]]
  from = "/api/health"
  to = "/.netlify/functions/health"  
  status = 200

[build.environment]
  NODE_VERSION = "18"